### ISSUE TITLE
Python 3.13 wheel 제공

### ISSUE THREAD

**Issue by item4** [tossicat/tossicat-python#1]
안녕하세요.

배포된 버전 확인해보았는데 wheel이 제공되는 버전중에 Python 3.13이 없는 것을 확인했습니다.

혹시 추가 가능하실까요?

**Comment by dev-bearabbit** [comment]
안녕하세요! 관심을 갖고 PR 보내주셔서 정말 감사합니다. 😊
코드 확인 후 병합을 완료했고, 버전 업데이트도 진행했습니다.

0.1.2 버전을 다운로드 하면 Python 3.13에서도 사용 가능하실 거예요!
감사합니다!
