### ISSUE TITLE
Cannot find reference 'postfix' in '__init__.py' 

### ISSUE THREAD

**Issue by item4** [tossicat/tossicat-python#3]
![Cannot find reference 'postfix' in '__init__.py' ](https://github.com/user-attachments/assets/a6226436-c513-408c-bd44-6d66fbc23a0c)

PyCharm에서 `tossicat.postfix` 등을 찾지 못합니다.

그 외에도 타입 힌트 등이 있으면 좋을 것 같습니다.

관련 문서: https://pyo3.rs/v0.23.0/python-typing-hints.html

**Comment by dev-bearabbit** [comment]
안녕하세요,
공유해주신 문서에 따라 pyi 파일을 추가하였습니다 :)

제가 PyCharm을 사용하지 않아 테스트는 못했지만 vscode나 mypy로 테스트 했을 때는 정상적으로 작동하는걸 확인했습니다.

- 0.1.2 version
```
__init__.py			tossicat.cpython-312-darwin.so
__pycache__
```

- 0.1.3 version
```
__init__.py			py.typed
__init__.pyi			tossicat.cpython-312-darwin.so
__pycache__
```

확인해보시고 추가적인 이슈가 있다면 알려주세요!

**Comment by item4** [comment]
잘 됩니다...! 감사합니다..!
